### ISSUE TITLE
Does not build on Linux Mint 20.3

### ISSUE THREAD

**Issue by bianchifan** [Embroidermodder/Embroidermodder#298]
cmake version 3.16 too old, so cmake 3.25 manually installed
build.sh runs into a cmake error:

CMake Error at CMakeLists.txt:86 (target_link_libraries):
  Cannot specify link libraries for target "imgui_embroidermodder" which is
  not built by this project.

**Comment by robin-swift** [comment]
Hi @bianchifan 

That was a holdover from an old build: I've fixed it. If you run `git pull; ./build.sh` it should work now.

I won't close the issue though, because if you have any other problems we can carry on discussing them here.

As for the CMake version number... it requires >=3.20 right now, I could see if an earlier version builds properly since Linux Mint 20.3 is pretty current and that has CMake 3.16.

Cheers,

Robin

**Comment by robin-swift** [comment]
Good spot: it ran fine with CMake 3.16 so I've updated that.

**Comment by bianchifan** [comment]
THX, but still no build..
The script tells 47% when an error occured:
 platform_string()’:
/home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:1220:39: error: no matching function for call to ‘to_string(char [65])’
 1220 |     os = std::to_string(buffer.sysname);
      |                                       ^
In file included from /usr/include/c++/9/string:55,
                 from /home/majo/tmp/Embroidermodder/extern/ImGuiColorTextEdit/TextEditor.h:3,
                 from /home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:20:
/usr/include/c++/9/bits/basic_string.h:6549:3: note: candidate: ‘std::string std::__cxx11::to_string(int)’ <near match>
 6549 |   to_string(int __val)
      |   ^~~~~~~~~
/usr/include/c++/9/bits/basic_string.h:6549:3: note:   conversion of argument 1 would be ill-formed:
/home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:1220:32: error: invalid conversion from ‘char*’ to ‘int’ [-fpermissive]
 1220 |     os = std::to_string(buffer.sysname);
      |                         ~~~~~~~^~~~~~~
      |                                |
      |                                char*
followed by a bunch of conversion errors.

**Comment by bianchifan** [comment]
THX, but still no build..
The script tells 47% when an error occured:
 platform_string()’:
/home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:1220:39: error: no matching function for call to ‘to_string(char [65])’
 1220 |     os = std::to_string(buffer.sysname);
      |                                       ^
In file included from /usr/include/c++/9/string:55,
                 from /home/majo/tmp/Embroidermodder/extern/ImGuiColorTextEdit/TextEditor.h:3,
                 from /home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:20:
/usr/include/c++/9/bits/basic_string.h:6549:3: note: candidate: ‘std::string std::__cxx11::to_string(int)’ <near match>
 6549 |   to_string(int __val)
      |   ^~~~~~~~~
/usr/include/c++/9/bits/basic_string.h:6549:3: note:   conversion of argument 1 would be ill-formed:
/home/majo/tmp/Embroidermodder/src/embroidermodder.cpp:1220:32: error: invalid conversion from ‘char*’ to ‘int’ [-fpermissive]
 1220 |     os = std::to_string(buffer.sysname);
      |                         ~~~~~~~^~~~~~~
      |                                |
      |                                char*
followed by a bunch of conversion errors.

**Comment by bianchifan** [comment]
THX!
Now it builds.
But it does not run, nor install :(

From ~/tmp/Embroidermodder/build it produces a dump
majo@majo-Studio-XPS-1340:~/tmp/Embroidermodder/build$ ./embroidermodder 
Reading Settings...
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  toml::parse: Error opening file "./settings.toml": iostream error
Abgebrochen (Speicherabzug geschrieben)

install
.
.
-- Up-to-date: /usr/share/embroidermodder/em2_config.toml
CMake Error at cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/home/majo/tmp/Embroidermodder/assets/default.toml": No such file or
  directory.

**Comment by bianchifan** [comment]
Just built successful on Ubuntu but it does not run..
settings.toml is missing

**Comment by robin-swift** [comment]
So the installer is broke, I've been building and running from build directory (try the `test.sh` script for example). I'll make that it's own issue.

As for the missing configuration file: that's because it doesn't check if this is the first time you've run the program. So I've just put a check in for that (my last commit at time of writing).

Try running `./test.sh`.

BTW thanks for sticking with this, it helps to have someone around testing this on other systems.

**Comment by bianchifan** [comment]
> Try running `./test.sh`.
> 

Yesterday evening I deleted all stuff and cloned completely new on a shared HOME partition.
Shared between my working system Linux MInt wih latest updates and a new  Testpartition Ubuntu 22.10 with latest updates.
Starting with test.sh shows the first error: no embroidermodder.exe! ;)
2nd try after correction.. Bild was done!
Unfortunately  embroidermodder does not run, GLIBC too old:
_majo@majo-Studio-XPS-1340:~/Embroidermodder/build$ ./embroidermodder
./embroidermodder: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./embroidermodder)
./embroidermodder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./embroidermodder)
./embroidermodder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./embroidermodder)
./embroidermodder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./embroidermodder)_

Status quo:
majo@majo-Studio-XPS-1340:~/Embroidermodder/build$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright © 2020 Free Software Foundation, Inc.
...

Build dir deleted and next try with Ubuntu:
Build was done!

When trying to start a black window flashes up for a short moment, crashes down immediately and writes a dump:
_majo@majo-Studio-XPS-1340:~/Embroidermodder/build$ ./embroidermodder
Reading Settings...
embroidermodder: /home/majo/Embroidermodder/extern/imgui/imgui_draw.cpp:2143: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
Abgebrochen (Speicherabzug geschrieben)
majo@majo-Studio-XPS-1340:~/Embroidermodder/build$_

**Comment by robin-swift** [comment]
I just made formatting changes to make that more legible.

The conclusions I can make from this are:

1. We need seperate test scripts for Linux and Windows because the binaries have different names. `test.bat` and `test.sh` for example.
2. We need a mechanism for checking what the minimum glibc version is: it appears to be something determined at compile time so this could be a non-trivial problem. It could be fixed by sticking to older versions of the C/C++ standards.
3. On Ubuntu the font loading mechanism is failing.

So I'm going to make two new issues for points 2 (#301) and 3 (#302) and solve issue 1 now.

That seems to be the end of this chain, see you in those issues.

**Comment by bianchifan** [comment]
New pull yesterday :

/media/majo/Daten/git/Embroidermodder/src/backend.c: In function ‘validRGB’:
/media/majo/Daten/git/Embroidermodder/src/backend.c:277:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
  277 |     if (isnan(r)) {
      |         ^~~~~
/media/majo/Daten/git/Embroidermodder/src/backend.c:281:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
  281 |     if (isnan(g)) {
      |         ^~~~~
/media/majo/Daten/git/Embroidermodder/src/backend.c:285:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
  285 |     if (isnan(b)) {
      |         ^~~~~
make[2]: *** [CMakeFiles/embroidermodder.dir/build.make:90: CMakeFiles/embroidermodder.dir/src/backend.c.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/embroidermodder.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
